'use strict';

const FETCH_USERS = 'FETCH_USERS';
const RECEIVE_USERS = 'RECEIVE_USERS';
const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';

module.exports = {
  FETCH_USERS,
  RECEIVE_USERS,
  FETCH_USERS_REJECTED
};
